### ISSUE TITLE
Autopilot bug

### ISSUE THREAD

**Issue by MarkBaggins** [tdammers/Douglas-Dc3#5] opened 2022-11-28 20:46 UTC
The Autopilot in the traditional layout is bugged

**Comment by tdammers** [comment] 2022-11-28 21:03
I'm afraid I need more information than that.

**Comment by MarkBaggins** [comment] 2022-11-28 22:03
Do you have discord or something so i could stream it to you?

**Comment by tdammers** [comment] 2022-11-28 22:13
Nope, and I'm not looking to sink substantial amounts of time into
"maintaining" anything here. This is my personal fork, you are welcome to
use it, send patches, and even report things, but I am not a support
hotline. You could explain the problem in more detail, and I might look
into it on an "if I feel like it" basis, but "it doesn't work" is useless,
and unless it breaks in ways that affect me personally, I am unlikely to
put any effort towards it.

A good bug report will contain the following key information:

1. What did you do?
2. What did you expect to happen?
3. What happened instead?
4. Potentially relevant context (FG version, OS, hardware, etc.)

**Comment by MarkBaggins** [comment] 2022-11-28 22:20
So the autopilot activated via the dile in the cockpit kinda works,the problem is that the rudder and elevator regulators (ap panel) seem to be kinda stuck,the move slightly but are held like by a rubberband, and one time i managed to unstuck it in a way, but not the intended way.
 This i the only real issue. I tryed both in .3 and .4 fg version,no change though

**Comment by tdammers** [comment] 2022-11-29 07:04
OK, so, the Sperry unit should work like this (off the top of my head, I
haven't used it in a while):

- The Elevator knob controls target pitch, and the autopilot matches it as
per the attitude indicator on the unit.
- The Rudder knob selects target heading, and the unit attempts to match
heading, as per the two parallel heading indicator discs on the unit; it
does not control banking.
- The Aileron knob controls target bank angle, as per the attitude
indicator on the unit.
- The Heading knob can be used to sync the heading indicator on the Sperry
unit with your actual heading (from mag or gyro compass).

To fly turns with this autopilot, you have to use both the rudder and
aileron controls.

First, use the heading knob to calibrate the Sperry unit's heading
indicator, set the target heading to your current heading with the rudder
knob, and, assuming you are flying straight and level, use the aileron and
elevator knobs to match the target attitude to the current one.

Turn on the autopilot.

Now use rudder and aileron knobs together: rudder to select target heading,
and aileron to set the desired bank angle. 25-30 degrees of bank should
produce a somewhat coordinated turn. Watch the heading discs carefully;
when you close in on your target heading, smoothly reduce bank angle with
the aileron knob, such that you reach neutral bank when reaching the target
heading.

Note specifically that if you only use the rudder knob, the aircraft will
attempt to make a turn while keeping the wings level, and the ailerons will
deflect opposite the desired turn to counter the rudder's banking moment,
and the resulting turn will be completely uncoordinated and slow as
molasses - OK for small corrections, but useless for proper turns.
Likewise, using the aileron knob alone will cause the unit to counter the
ailerons' yaw moment and frantically attempt to keep the aircraft on course
with rudder alone, creating a side slip.

IRL, pilots would twist both knobs at the same time, but this is tricky in
the sim (unless you have physical knobs assigned to them); what I've found
works OK is to first move the rudder knob in the general direction of the
turn, then quickly move over to the ailerons, get the right bank angle in,
and then set the rudder disc to the precise target heading.

And keep in mind that the purpose of the device was not to actually fly the
aircraft through all sorts of maneuvers, the main goal was to allow the
pilots to stretch their arms and legs for a while on long flights, and they
would generally use it for straight and level flight in cruise, and little
else. It is perfectly adequate for that.

Anyway, this is how it should work, and last time I tried, it worked as
designed. If it doesn't, despite following the above procedures, I'd like
to know what happens instead, and also what FG version you're running.

Oh, and, just to rule this one out: this repo is not the version found in
the launcher (fgaddon). That one is maintained by helijah, so for any
questions on it, you will have to track him down and establish
communication (and please don't ask him about my version, he seems a bit
offended by its existence). Anyway, the Sperry unit in the helijah version
is implemented incorrectly and does not work like the real one; mine should
be more faithful, though finding proper documentation for an aircraft
system designed over 70 years ago.

**Comment by MarkBaggins** [comment] 2022-11-29 11:49
I imagined thqt the ap isnt a adirs gps thing,but the issue is that the diles just dont move,the only one is the ap "switch", if you want to try it, and it works, could then tell me some info. another thing; i found somewhere a buffalo airways dc3 livery, on github, but its not in yours,if you want,i could send it to you,just tell me how. 
Thanks for all your support

Ps: Sorry for bad writing but am writing with my phone

**Comment by tdammers** [comment] 2022-11-29 12:53
I see what you mean now, and it seems to be an actual bug, something seems
to be messing with those inputs. Sorry for the somewhat dismissive
responses earlier, I'll take a closer look when I can find the time.

**Comment by MarkBaggins** [comment] 2022-11-29 13:07
Thanks, let me know for the buffalo airways livery

**Comment by tdammers** [comment] 2022-11-29 13:11
Oh, right; easiest for me would be a github PR, I guess.

If that's not an option, you could also email me the files
***@***.***).

One condition, however, is that they're license-compatible with what's
already there, which means they must be GPL 2.0, or any of the
permissive open-source licenses that allow redistributing under GPL 2.0
(e.g. MIT, BSD); specifically, GPL 3.0 and most of the CC licenses are
*not* compatible, so if that livery comes with one of those, I can't
include it.

**Comment by MarkBaggins** [comment] 2022-11-29 13:17
I found the livery in some dc3 fork on github,ill look for it

**Comment by MarkBaggins** [comment] 2022-11-29 13:23
The livery seems to come from the fgmember's dc3 gpl-2 under the name bfl

**Comment by tdammers** [comment] 2022-11-29 13:35
Ah, in that case I'll decline - the problem with fgmembers is that as
far as licenses and copyright are concerned, all bets are off. The
fgmembers group has a history of just grabbing whatever FG content they
could find and redistributing it, with little or no concern about
licensing, and that unfortunately means that the license on the box may
not be valid in the first place.

So as much as I'd love a Buffalo livery on the 3, I'd rather not burn my
fingers on this.

**Comment by MarkBaggins** [comment] 2022-11-29 14:59
ah ok np

**Comment by tdammers** [comment] 2022-11-30 09:39
Sperry autopilot bug has been fixed, should work as designed now. Feel free to reopen if it's still not working.

**Closed as completed by tdammers** 2022-11-30 09:39 UTC
